### ISSUE TITLE
Hi Aaron!

### ISSUE THREAD

**Issue by mixelpixel** [Arkoma/chained-up#1]
Just testing the issues interface as a means for TAs to make comments on these projects. This should get you an email? Please DM me in Slack if you get an email notice regarding this comment, thanks!

**Comment by Arkoma** [comment]
I did not get the email. I think this has to be watched to get get email notifications

**Comment by mixelpixel** [comment]
🤔  hmm... I _hope_ that's not the case... If you would be so kind, could you drop a comment here on one of my repositories?

https://github.com/mixelpixel/Learn-C-The-Hard-Way/issues

I'll see if I get an email notice. Seems odd that if someone opened an "issue" on a GH repo that the owner _wouldn't_ get an email.... 💩

**Comment by mixelpixel** [comment]
Totally different issue, but odd too that your GH profile pic shows up in Slack every time you post one of your GH repositories... Whatevers... I gotta go get some ☕️  Thanks for poking at this with me :)

**Comment by Arkoma** [comment]
I’m closing this. I don’t know why the profile pic does that either
